"""
Core domain models shared across the platform.
These are the common data structures that flow between modules.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Timeframe(Enum):
    """Candle timeframe intervals."""

    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    D1 = "1d"


class SignalType(Enum):
    """Trading signal direction."""

    BUY = "BUY"
    SELL = "SELL"


class OrderSide(Enum):
    """Order side for paper trades."""

    BUY = "BUY"
    SELL = "SELL"


class PositionStatus(Enum):
    """Position lifecycle status."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"


@dataclass
class Candle:
    """OHLCV candle built from ticks."""

    exchange: str
    segment: str
    exchange_token: str
    timeframe: Timeframe
    timestamp_ms: float  # candle open time
    open: float
    high: float
    low: float
    close: float
    volume: int = 0

    def __repr__(self) -> str:
        return (
            f"Candle({self.exchange_token} {self.timeframe.value} "
            f"O={self.open:.2f} H={self.high:.2f} L={self.low:.2f} C={self.close:.2f})"
        )


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    signal_type: SignalType
    exchange: str
    segment: str
    exchange_token: str
    price: float
    timestamp_ms: float
    strategy_name: str
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def __repr__(self) -> str:
        return (
            f"Signal({self.signal_type.value} {self.exchange_token} "
            f"@{self.price:.2f} by {self.strategy_name})"
        )


@dataclass
class PaperOrder:
    """A simulated order in the paper trading engine."""

    order_id: str
    side: OrderSide
    exchange: str
    segment: str
    exchange_token: str
    quantity: int
    price: float
    timestamp_ms: float
    strategy_name: str
    signal_reason: str = ""


@dataclass
class Position:
    """A tracked position (open or closed)."""

    position_id: str
    exchange: str
    segment: str
    exchange_token: str
    side: OrderSide
    quantity: int
    entry_price: float
    entry_time_ms: float
    strategy_name: str
    status: PositionStatus = PositionStatus.OPEN
    exit_price: float = 0.0
    exit_time_ms: float = 0.0
    pnl: float = 0.0
    pnl_pct: float = 0.0

    @property
    def is_open(self) -> bool:
        return self.status == PositionStatus.OPEN

    def close(self, exit_price: float, exit_time_ms: float) -> None:
        """Close the position and calculate PnL."""
        self.exit_price = exit_price
        self.exit_time_ms = exit_time_ms
        self.status = PositionStatus.CLOSED

        if self.side == OrderSide.BUY:
            self.pnl = (self.exit_price - self.entry_price) * self.quantity
        else:
            self.pnl = (self.entry_price - self.exit_price) * self.quantity

        if self.entry_price > 0:
            self.pnl_pct = (self.pnl / (self.entry_price * self.quantity)) * 100

    def __repr__(self) -> str:
        status = "OPEN" if self.is_open else f"CLOSED PnL={self.pnl:.2f}"
        return (
            f"Position({self.side.value} {self.exchange_token} "
            f"qty={self.quantity} @{self.entry_price:.2f} [{status}])"
        )
